---
id: jonah
name: Jonah
full: Newsfeed application
description: |
  Jonah is a portal system for displaying news and other data
  from various sources, written in PHP and utilizing the Horde Application
  Framework.
list: horde
type: application
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.php.net/DB: '*'
